<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Beta-diversity Analysis with hagis • hagis</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/journal/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Beta-diversity Analysis with hagis">
<meta property="og:description" content="hagis">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">hagis</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.1.3</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/hagis.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/betadiversity.html">Beta-diversity Analysis with hagis</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/openplantpathology/hagis/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="betadiversity_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Beta-diversity Analysis with hagis</h1>
                        <h4 class="author">Austin McCoy</h4>
            
            <h4 class="date">2021-10-25</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/openplantpathology/hagis/blob/master/vignettes/betadiversity.Rmd"><code>vignettes/betadiversity.Rmd</code></a></small>
      <div class="hidden name"><code>betadiversity.Rmd</code></div>

    </div>

    
    
<div id="load-packages" class="section level1">
<h1 class="hasAnchor">
<a href="#load-packages" class="anchor"></a>Load Packages</h1>
<p>These packages are necessary for this analysis to be conducted.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="http://ape-package.ird.fr/">"ape"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://cran.r-project.org">"vegan"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://dplyr.tidyverse.org">"dplyr"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/openplantpathology/hagis">"hagis"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://ggplot2.tidyverse.org">"ggplot2"</a></span><span class="op">)</span></code></pre></div>
<p>Import the data to be used in analysis. These example data are included in <em>hagis</em> and so when loading <em>hagis</em> they become available in your R session.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">P_sojae_survey</span><span class="op">)</span> <span class="co"># survey sample data</span></code></pre></div>
<pre><code>##    Isolate         Line         Rps Total HR (1) Lesion (2)
## 1:       1     Williams susceptible    10      0          0
## 2:       1       Harlon      Rps 1a    10      4          0
## 3:       1 Harosoy 13xx      Rps 1b     8      0          0
## 4:       1     L75-3735      Rps 1c    10     10          0
## 5:       1    PI 103091      Rps 1d     9      2          0
## 6:       1  Williams 82      Rps 1k    10      0          0
##    Lesion to cotyledon (3) Dead (4) total.susc total.resis perc.susc perc.resis
## 1:                       0       10         10           0       100          0
## 2:                       0        6          6           4        60         40
## 3:                       0        8          8           0       100          0
## 4:                       0        0          0          10         0        100
## 5:                       1        6          7           2        78         22
## 6:                       0       10         10           0       100          0</code></pre>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sample_meta</span><span class="op">)</span> <span class="co"># metatada about the sample collection locations</span></code></pre></div>
<pre><code>##   Sample   Locale
## 1      1 Michigan
## 2     10 Michigan
## 3     11 Michigan
## 4     12 Michigan
## 5     13 Michigan
## 6     14 Michigan</code></pre>
<p>This removes the “MPS17_” from the isolates, so that they will be read as numeric instead of character. The next step removes the “Rps” from the gene names, so that they will be read as numeric instead of character.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">P_sojae_survey</span><span class="op">$</span><span class="va">Isolate</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span>pattern <span class="op">=</span> <span class="st">"MPS17_"</span>,
       replacement <span class="op">=</span> <span class="st">""</span>,
       x <span class="op">=</span> <span class="va">P_sojae_survey</span><span class="op">$</span><span class="va">Isolate</span><span class="op">)</span>
<span class="va">P_sojae_survey</span><span class="op">$</span><span class="va">Rps</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span>pattern <span class="op">=</span> <span class="st">"Rps "</span>,
       replacement <span class="op">=</span> <span class="st">""</span>,
       x <span class="op">=</span> <span class="va">P_sojae_survey</span><span class="op">$</span><span class="va">Rps</span><span class="op">)</span></code></pre></div>
<p>Set up the <em>hagis</em> arguments for analysis. Please see <code><a href="../articles/hagis.html">vignette("hagis")</a></code> for more details on how to specify arguments for the functions in this package.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hagis_args</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
  x <span class="op">=</span> <span class="va">P_sojae_survey</span>,
  cutoff <span class="op">=</span> <span class="fl">60</span>,
  control <span class="op">=</span> <span class="st">"susceptible"</span>,
  sample <span class="op">=</span> <span class="st">"Isolate"</span>,
  gene <span class="op">=</span> <span class="st">"Rps"</span>,
  perc_susc <span class="op">=</span> <span class="st">"perc.susc"</span>
<span class="op">)</span></code></pre></div>
</div>
<div id="convert-the-dataset-to-a-binary-data-matrix" class="section level1">
<h1 class="hasAnchor">
<a href="#convert-the-dataset-to-a-binary-data-matrix" class="anchor"></a>Convert the Dataset to a Binary Data Matrix</h1>
<p>Using <code><a href="../reference/create_binary_matrix.html">create_binary_matrix()</a></code> transforms the data so that it is in the correct format (binary data matrix) for PCOA analysis.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">P_sojae_survey.matrix</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">create_binary_matrix</span>, <span class="va">hagis_args</span><span class="op">)</span>

<span class="va">P_sojae_survey.matrix</span></code></pre></div>
<pre><code>##    1a 1b 1c 1d 1k 2 3a 3b 3c 4 5 6 7
## 1   1  1  0  1  1 1  1  1  0 0 1 1 1
## 10  1  0  1  0  0 0  0  1  0 0 1 0 1
## 11  1  0  1  0  0 0  0  1  0 0 1 1 1
## 12  1  1  1  1  1 1  0  0  0 0 0 1 1
## 13  1  1  1  1  1 0  0  1  0 0 0 0 1
## 14  1  1  1  0  1 0  0  1  0 0 1 1 1
## 15  1  1  1  1  1 1  0  1  0 1 1 1 1
## 16  1  1  1  0  1 0  0  1  0 0 1 0 1
## 17  1  1  1  1  1 1  0  1  0 1 1 0 1
## 18  1  1  1  1  1 0  1  1  0 0 1 1 1
## 19  1  1  1  1  1 1  1  1  1 0 0 1 1
## 2   1  1  1  0  1 1  0  1  1 1 0 1 1
## 20  1  1  1  1  1 1  1  1  1 0 1 0 1
## 21  1  1  1  1  1 1  1  1  1 1 1 1 1
## 3   1  1  1  1  1 1  0  1  0 1 0 1 1
## 4   1  0  1  1  1 1  0  1  0 0 1 0 1
## 5   1  0  1  1  1 1  0  1  0 0 0 1 1
## 6   1  0  1  1  1 1  0  1  0 0 1 0 1
## 7   1  1  1  1  1 1  0  1  0 0 0 0 1
## 8   1  1  1  1  1 1  0  1  0 0 0 0 1
## 9   1  0  1  1  0 0  0  1  0 0 1 0 1</code></pre>
<p>The <code>P_sojae_survey.matrix</code> object contains the RPS genes numbered as rows and the columns are numbered isolates. A “1” indicates the isolate caused disease on the RPS gene, and a “0” means it did not.</p>
</div>
<div id="perform-principle-coordinates-analysis-pcoa" class="section level1">
<h1 class="hasAnchor">
<a href="#perform-principle-coordinates-analysis-pcoa" class="anchor"></a>Perform Principle Coordinates Analysis (PCOA)</h1>
<p>The following code will transpose the <code>P_sojae_survey.matrix</code> and then calculate the Jaccard distances for each isolate. Jaccard distance calculations need to be used as pathotype data is presence/absence for virulence. Lastly, PCOA is performed to identify the variance explained by each principal coordinate. This will be used later to visualize and identify distance pathotype groupings by geographic location. In this example, Jaccard distances are used as this is presence/absence data.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">P_sojae_survey.matrix.jaccard</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/pkg/vegan/man/vegdist.html">vegdist</a></span><span class="op">(</span><span class="va">P_sojae_survey.matrix</span>, <span class="st">"jaccard"</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>After performing the principal coordinates analysis, we see that the scree plot says that about 70% of the variation in Jaccard distances are explained within the first two dimensions (<em>i.e.</em>, axes). This is good. Usually a good rule of thumb is that if the second dimension is roughly half variation explained in the first dimension you don’t need to look further at the third or n+1 dimensions.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">princoor.pathotype</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ape/man/pcoa.html">pcoa</a></span><span class="op">(</span><span class="va">P_sojae_survey.matrix.jaccard</span><span class="op">)</span> 

<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">princoor.pathotype</span><span class="op">$</span><span class="va">values</span><span class="op">$</span><span class="va">Relative_eig</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<p><img src="betadiversity_files/figure-html/barplot-1.png" width="700"></p>
<p>Now we can calculate the percentage of variation that each principal coordinate accounts for. Another way to calculate the percent variation is to look at the <code>Relative_eig</code> column.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Dimension (i.e., Axis 1 (PCOA1))</span>
<span class="va">Axis1.percent</span> <span class="op">&lt;-</span>
  <span class="va">princoor.pathotype</span><span class="op">$</span><span class="va">values</span><span class="op">$</span><span class="va">Relative_eig</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span> <span class="op">*</span> <span class="fl">100</span>

<span class="co"># Dimension (i.e., Axis 2 (PCOA2))</span>
<span class="va">Axis2.percent</span> <span class="op">&lt;-</span>
  <span class="va">princoor.pathotype</span><span class="op">$</span><span class="va">values</span><span class="op">$</span><span class="va">Relative_eig</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span> <span class="op">*</span> <span class="fl">100</span>

<span class="va">Axis1.percent</span></code></pre></div>
<pre><code>## [1] 50.39109</code></pre>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Axis2.percent</span></code></pre></div>
<pre><code>## [1] 21.79118</code></pre>
<p>Now we can make a data frame with the two principal coordinates that account for the most variation in the data. We will then add metadata to the data frame <code>pca.data</code>.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">princoor.pathotype.data</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>
    Sample <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">princoor.pathotype</span><span class="op">$</span><span class="va">vectors</span><span class="op">)</span><span class="op">)</span>,
    X <span class="op">=</span> <span class="va">princoor.pathotype</span><span class="op">$</span><span class="va">vectors</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,
    Y <span class="op">=</span> <span class="va">princoor.pathotype</span><span class="op">$</span><span class="va">vectors</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>
  <span class="op">)</span></code></pre></div>
</div>
<div id="add-metadata-to-your-pcoa-data" class="section level1">
<h1 class="hasAnchor">
<a href="#add-metadata-to-your-pcoa-data" class="anchor"></a>Add Metadata to your PCOA Data</h1>
<p>You will need to add information on the sample collection location or other data to help identify different pathotype groupings based on geographic location or other factors. We will use <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> from <em>dplyr</em> to combine the <code>princoor.pathotype.data</code> with the metadata that we’ve already loaded, <code>sample_meta</code> that contains a geographic location (state name).</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">princoor.pathotype.data</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">princoor.pathotype.data</span>, <span class="va">sample_meta</span>, by <span class="op">=</span> <span class="st">"Sample"</span><span class="op">)</span>

<span class="va">princoor.pathotype.data</span></code></pre></div>
<pre><code>##    Sample            X           Y   Locale
## 1       1  0.127655783  0.08704548 Michigan
## 2      10 -0.441075005  0.01573886 Michigan
## 3      11 -0.336826428  0.21804192 Michigan
## 4      12  0.217071376 -0.03795693 Michigan
## 5      13 -0.003862869 -0.14942952 Michigan
## 6      14 -0.108034781  0.18124849 Michigan
## 7      15  0.082862290  0.06501932 Michigan
## 8      16 -0.182559838  0.01610323 Michigan
## 9      17  0.043684771 -0.07086878 Michigan
## 10     18 -0.007048533  0.11629976 Michigan
## 11     19  0.224528803  0.06847162 Michigan
## 12      2  0.190565779  0.16984304 Michigan
## 13     20  0.081014587 -0.01986841 Michigan
## 14     21  0.156490576  0.15103874 Michigan
## 15      3  0.187665103  0.01477482 Michigan
## 16      4 -0.088772478 -0.14970662 Michigan
## 17      5  0.069295886 -0.06198926 Michigan
## 18      6 -0.088772478 -0.14970662 Michigan
## 19      7  0.102108599 -0.17330058 Michigan
## 20      8  0.102108599 -0.17330058 Michigan
## 21      9 -0.328099742 -0.11749798 Michigan</code></pre>
<p>Now we will plot the PCA data using <em>ggplot2</em> and color the points based on location, <code>Locale</code>, and identify the 95% confidence interval of those groups using the <code><a href="https://ggplot2.tidyverse.org/reference/stat_ellipse.html">stat_ellipse()</a></code> function.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">princoor.pathotype.data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">X</span>, y <span class="op">=</span> <span class="va">Y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="va">Locale</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"PCOA1 - "</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">Axis1.percent</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"%"</span>, sep <span class="op">=</span> <span class="st">""</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"PCOA2 - "</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">Axis2.percent</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"%"</span>, sep <span class="op">=</span> <span class="st">""</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>
    axis.title.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">15</span><span class="op">)</span>,
    axis.title.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">15</span><span class="op">)</span>,
    axis.text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>,
    legend.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>,
    legend.text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>face <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>,
    legend.key.size <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/unit.html">unit</a></span><span class="op">(</span><span class="fl">1</span>, <span class="st">'lines'</span><span class="op">)</span>
  <span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_ellipse.html">stat_ellipse</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">princoor.pathotype.data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">X</span>, y <span class="op">=</span> <span class="va">Y</span><span class="op">)</span>,
               level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Pathotype Jaccard Distances PCOA"</span><span class="op">)</span></code></pre></div>
<p><img src="betadiversity_files/figure-html/ggplot-pca-1.png" width="700"></p>
</div>
<div id="statistical-tests-for-beta-diversity" class="section level1">
<h1 class="hasAnchor">
<a href="#statistical-tests-for-beta-diversity" class="anchor"></a>Statistical Tests for Beta Diversity</h1>
<p>When using two or more pathotype datasets for comparisons, you can use beta-diversity tests to identify if there are significant differences between their sampled pathotype compositions. These code are presented as an example for further downstream analysis that can be used when comparing two or more populations’ pathotype composition.</p>
<p>In these examples we will artificially split the dataset into two, so that these analyses can be shown. When performing your own analyses you will likely have two geographic locations to compare already. Make sure you can differentiate these populations with the metadata file used previously (<em>i.e.</em>, column in the dataset that specifies where the isolate came from; USA, Brazil, China, Australia, etc.).</p>
</div>
<div id="permutation-based-analysis-of-variance-permanova-and-beta-dispersion-analyses" class="section level1">
<h1 class="hasAnchor">
<a href="#permutation-based-analysis-of-variance-permanova-and-beta-dispersion-analyses" class="anchor"></a>Permutation Based Analysis of Variance (PERMANOVA) and Beta-dispersion Analyses</h1>
<div id="beta-dispersion" class="section level2">
<h2 class="hasAnchor">
<a href="#beta-dispersion" class="anchor"></a>Beta-Dispersion</h2>
<p>Beta-dispersion tests if the dispersion, variance, of two or more groups are significantly different or not. First, an item named “groups” must be made that contains lists of the location and number of isolates from that location used in the analysis. We will then check to make sure the lists in “groups” adds up to the number of isolated used in analysis.</p>
<p>First, make a list of the locations for each pathotype. Note that when you are using two or more locations you will need to make a list for each location with a length of isolates used.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">groups</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Michigan_1"</span>, <span class="fl">11</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Michigan_2"</span>, <span class="fl">10</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="co"># this number shows how many isolates are in all "groups" lists combined</span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">groups</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 21</code></pre>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># this shows the number of isolates within your data set, these numbers should</span>
<span class="co"># match for downstream analyses to work!! </span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">P_sojae_survey</span><span class="op">$</span><span class="va">Isolate</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 21</code></pre>
<p>Next, beta-dispersion will be calculated using the Jaccard distance matrix made previously. An ANOVA is then performed to identify significance within the dataset. Post-hoc tests can be used to identify significant interactions between specific locations within the dataset. This can then be plotted to visualize how the beta-dispersion is different between groups.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"> <span class="co"># calculates the beta-dispersion for each group, when comparing 2 or more</span>
<span class="va">pathotype.disp</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/pkg/vegan/man/betadisper.html">betadisper</a></span><span class="op">(</span><span class="va">P_sojae_survey.matrix.jaccard</span>, <span class="va">groups</span><span class="op">)</span>

<span class="co"># tests if centroid distances are significantly different from each other</span>
<span class="va">pathotype.disp.anova</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">pathotype.disp</span><span class="op">)</span> 
<span class="va">pathotype.disp.anova</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Distances
##           Df   Sum Sq   Mean Sq F value Pr(&gt;F)
## Groups     1 0.008375 0.0083752  0.9672 0.3377
## Residuals 19 0.164523 0.0086591</code></pre>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># test significance between each group</span>
<span class="va">pathotype.disp.TukeyHSD</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="va">pathotype.disp</span><span class="op">)</span>
<span class="va">pathotype.disp.TukeyHSD</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = distances ~ group, data = df)
## 
## $group
##                              diff        lwr        upr     p adj
## Michigan_2-Michigan_1 -0.03998626 -0.1250853 0.04511275 0.3377355</code></pre>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot showing the dispersion for each group</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">pathotype.disp</span>, hull <span class="op">=</span> <span class="cn">FALSE</span>, ellipse <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="betadiversity_files/figure-html/beta-dispersion-1.png" width="700"></p>
<p>The ANOVA identified no significant differences between groups dispersion (p = 0.3377355). This means that the groups dispersion, or variance, is not significantly different from each other and the groups dispersion is likely homogeneous between groups. At this point, a Tukey HSD test is not warranted, but we use it as an example here. Again, a p-value of 0.3377355 is reported from the Tukey HSD tests and we reject the hypothesis that these groups may have different dispersion. We can plot the dispersion for each group using the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> function. As expected, since we have identified no significant differences, the two groups dispersion overlap a great deal and are not distinct from each other. Again this shows that pathotype dispersion between the groups is homogeneous and not different in this instance.</p>
<p>If we were working with a data set that had groups with significantly different dispersion we would expect to see a significant ANOVA p-value (p &lt; 0.05) as well as significance when using the Tukey HSD test. Lastly, the plotted dispersion will form distinct, separate, groups which can be observed.</p>
<p>Differences in beta-dispersion may indicate separate pathotype groups which should be further investigated with Permutation Based Analysis of Variance (PERMANOVA) and Analysis of Similarity (ANOSIM) analysis. Groups which have similar dispersion may still be significantly different in regards to their centroids, which will be tested using a PERMANOVA.</p>
</div>
<div id="permutation-based-analysis-of-variance-permanova" class="section level2">
<h2 class="hasAnchor">
<a href="#permutation-based-analysis-of-variance-permanova" class="anchor"></a>Permutation Based Analysis of Variance (PERMANOVA)</h2>
<p>PERMANOVA tests if the centroids, similar to means, of each group are significantly different from each other. Likewise, an <span class="math inline">\(R^2\)</span> statistic is calculated, showing the percentage of the variance explained by the groups.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pathotype.adonis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/vegan/man/adonis.html">adonis</a></span><span class="op">(</span><span class="va">P_sojae_survey.matrix.jaccard</span> <span class="op">~</span> <span class="va">groups</span><span class="op">)</span>

<span class="va">pathotype.adonis</span></code></pre></div>
<pre><code>## 
## Call:
## adonis(formula = P_sojae_survey.matrix.jaccard ~ groups) 
## 
## Permutation: free
## Number of permutations: 999
## 
## Terms added sequentially (first to last)
## 
##           Df SumsOfSqs  MeanSqs F.Model      R2 Pr(&gt;F)
## groups     1   0.11358 0.113583  1.6229 0.07869  0.212
## Residuals 19   1.32976 0.069988         0.92131       
## Total     20   1.44335                  1.00000</code></pre>
<p>The PERMANOVA identified no significant differences between the groups centroids, or means (<em>p</em> = 0.212). In addition to identifying significance between group centroids, the PERMANOVA also calculates how much of the variance can be explained by the specified groups (see the <span class="math inline">\(R^2\)</span> column in the PERMANOVA output). In this case, the <span class="math inline">\(R^2\)</span> is 0.212, so 21.2% of the variance is explained by the groups used in analysis. Based on the PERMANOVA results we can conclude that these two groups are not different from each other and likely have similar pathotypes to each other.</p>
</div>
<div id="analysis-of-similarity-anosim" class="section level2">
<h2 class="hasAnchor">
<a href="#analysis-of-similarity-anosim" class="anchor"></a>Analysis of Similarity (ANOSIM)</h2>
<p>ANOSIM statistic (R) ranges from between -1 and 1. Positive numbers suggest that there is more similarity within groups than there is between groups. Values close to zero indicate no difference between groups (<em>i.e.</em>, similarities are the same between groups).</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pathotype.anosim</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/vegan/man/anosim.html">anosim</a></span><span class="op">(</span><span class="va">P_sojae_survey.matrix.jaccard</span>, <span class="va">groups</span><span class="op">)</span>

<span class="va">pathotype.anosim</span></code></pre></div>
<pre><code>## 
## Call:
## anosim(x = P_sojae_survey.matrix.jaccard, grouping = groups) 
## Dissimilarity: jaccard 
## 
## ANOSIM statistic R: 0.06882 
##       Significance: 0.157 
## 
## Permutation: free
## Number of permutations: 999</code></pre>
<p>ANOSIM statistic (R) was 0.0688182, so there are more similarities between groups than there are within groups. This is evidence that the groups are not different from one another. Likewise the significance is &gt;0.05 so there is no significant difference between groups’ similarities.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Austin G. McCoy, Zachary Noel, Adam H. Sparks, Martin Chilvers, Michigan Soybean Promotion Committee, Project GREEEN, North Central Soybean Research Program, GRDC Project DAQ00186.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
