#' Calculate Distribution of Complexities by Sample
#'
#' @description Calculate the distribution of susceptibilities by sample id.
#'
#' @inheritParams summarize_gene
#' @examplesIf interactive()
#'
#' # Using the built-in data set, `P_sojae_survey`
#' data(P_sojae_survey)
#'
#' P_sojae_survey
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' complexities <- calculate_complexities(
#'   x = P_sojae_survey,
#'   cutoff = 60,
#'   control = "susceptible",
#'   sample = "Isolate",
#'   gene = "Rps",
#'   perc_susc = "perc.susc"
#' )
#' complexities
#'
#' summary(complexities)
#'
#' @returns An object of class `hagis.complexities`.
#'
#' An object of class `hagis.complexities` is a `list` containing the following
#'  components
#'   \describe{
#'     \item{grouped_complexities}{a [data.table::data.table()] object of
#'       grouped complexities}
#'     \item{individual_complexities}{a [data.table::data.table()] object of
#'       individual complexities}
#'   }
#'
#' @autoglobal
#' @export calculate_complexities

calculate_complexities <- function(
  x,
  cutoff,
  control,
  sample,
  gene,
  perc_susc
) {
  # check inputs and rename columns to work with this package
  x <- .check_inputs(
    .x = x,
    .cutoff = cutoff,
    .control = control,
    .sample = sample,
    .gene = gene,
    .perc_susc = perc_susc
  )

  # Remove susceptible control so it does not affect complexity calculations
  x <- x[gene != control]

  # Create susceptible.1 binary column
  x <- .binary_cutoff(.x = x, .cutoff = cutoff)

  # Individual isolate complexities: count susceptible reactions per sample
  individual_complexities <- .create_summary_isolate(.y = x)

  n_sample <- length(unique(x[["sample"]]))

  # Replace for-loop + utils::stack() with a single vectorised aggregation.
  # Count isolates at each complexity level, then compute percentage frequency.
  grouped_complexities <- individual_complexities[,
    list(distribution = .N, frequency = .N / n_sample * 100),
    by = N_samp
  ]

  # Ensure every complexity level from 1..n_gene is represented (fill zeros)
  n_gene <- length(unique(x[["gene"]]))
  all_levels <- data.table(N_samp = seq_len(n_gene))
  grouped_complexities <- grouped_complexities[
    all_levels,
    on = "N_samp"
  ]
  grouped_complexities[is.na(distribution), distribution := 0L]
  grouped_complexities[is.na(frequency), frequency := 0]

  setnames(grouped_complexities, "N_samp", "complexity")
  setcolorder(
    grouped_complexities,
    c("complexity", "frequency", "distribution")
  )
  setorder(grouped_complexities, complexity)

  complexities <- list(
    grouped_complexities = grouped_complexities,
    individual_complexities = individual_complexities
  )

  # Set new class
  class(complexities) <- union("hagis.complexities", class(x))
  return(complexities)
}

#' Plot hagis Complexities Objects
#'
#' @description Creates a \CRANpkg{ggplot2} object of the frequency of
#'  complexity (percent per complexity) or a \CRANpkg{ggplot2} object of the
#'  distribution (number per complexity) calculated by
#'  [calculate_complexities()].
#' @param object a \CRANpkg{hagis} `complexities` object generated by
#'  [calculate_complexities()]. `Character`.
#' @param type a vector of values for which the bar plot is desired. Specify
#'  whether to return a graph of the frequency of complexities as a percentage,
#'  "`percentage`", or as the count, "`count`". `Character`.
#' @param color a named or hexadecimal color value to use for the bar color
#' @param order sort the x-axis of the bar chart by ascending or descending
#' order of `frequency`. Accepts `ascending` or `descending` input values.
#' Defaults to `complexity` value. `Character`.
#' @param ... passed to the chosen `geom(s)`
#'
#' @autoglobal
#' @examplesIf interactive()
#' # Using the built-in data set, `P_sojae_survey`
#' data(P_sojae_survey)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' complexities <- calculate_complexities(
#'   x = P_sojae_survey,
#'   cutoff = 60,
#'   control = "susceptible",
#'   sample = "Isolate",
#'   gene = "Rps",
#'   perc_susc = "perc.susc"
#' )
#'
#' # Visualize the distribution (count or actual values)
#' autoplot(complexities, type = "count")
#'
#' # Visualize the frequency (percentages)
#' autoplot(complexities, type = "percentage")
#'
#' @returns A \CRANpkg{ggplot2} object
#' @method autoplot hagis.complexities
#' @export

autoplot.hagis.complexities <-
  function(object, type, color = NULL, order = NULL, ...) {
    z <- object[[1L]]

    # order cols based on user input
    if (!is.null(order)) {
      if (order == "ascending") {
        setorder(z, frequency)
      } else if (order == "descending") {
        setorder(z, -frequency)
      }
    } else {
      setorder(z, complexity)
    }
    z$order <- seq_len(nrow(z))

    plot_percentage <- function(.data, .color) {
      perc_plot <- ggplot2::ggplot(
        data = .data,
        ggplot2::aes(
          x = stats::reorder(complexity, order),
          y = frequency
        )
      ) +
        ggplot2::labs(
          y = "Percent of samples",
          x = "Complexity"
        ) +
        ggplot2::ggtitle("Percentage of isolates per complexity")

      if (!is.null(.color)) {
        perc_plot + ggplot2::geom_col(fill = .color, colour = .color, ...)
      } else {
        perc_plot + ggplot2::geom_col(...)
      }
    }

    plot_count <- function(.data, .color) {
      num_plot <- ggplot2::ggplot(
        data = .data,
        ggplot2::aes(
          x = stats::reorder(complexity, order),
          y = distribution
        )
      ) +
        ggplot2::labs(
          y = "Number of samples",
          x = "Complexity"
        ) +
        ggplot2::ggtitle("Number of samples per pathotype complexity")

      if (!is.null(.color)) {
        num_plot + ggplot2::geom_col(fill = .color, colour = .color, ...)
      } else {
        num_plot + ggplot2::geom_col(...)
      }
    }

    if (type == "percentage") {
      plot_percentage(.data = z, .color = color)
    } else if (type == "count") {
      plot_count(.data = z, .color = color)
    } else {
      stop(call. = FALSE, "You have entered an invalid `type`.")
    }
  }

#' Create Summary Table of Binary Reactions by Sample
#'
#' Tally a summary by sample or isolate. This code takes the "Susceptible.1"
#'  column and summarises it by gene for your total "Isolates" pathogenic on
#'  each sample.
#'
#' @param .y A \CRANpkg{hagis} `complexities` object generated by
#'  [calculate_complexities()]. `Character`.
#' @returns A `data.table` that tallies the results by sample.
#' @autoglobal
#' @dev
.create_summary_isolate <- function(.y) {
  .y[, list(N_samp = sum(susceptible.1)), by = list(sample)]
}

#' Summarises {hagis} Complexity Objects
#'
#' Custom [summary()] method for \pkg{hagis} `complexities` objects.
#'
#' @param object A hagis class object (a list of two `data.table`s)
#' @param ... ignored
#' @noRd
#' @export
summary.hagis.complexities <- function(object, ...) {
  vals <- object$individual_complexities$N_samp
  x <- data.frame(
    mean = mean(vals),
    sd = stats::sd(vals),
    se = sqrt(stats::var(vals) / length(vals))
  )
  class(x) <- "summary.complexities"
  x
}

#' Prints summary.hagis Object for Complexities
#'
#' Custom [print()] method for \CRANpkg{hagis} `summary.complexity` objects.
#'
#' @param x a summary.complexities object
#' @param digits number of digits to print
#' @param ... ignored
#' @export
#' @noRd
print.summary.complexities <- function(
  x,
  digits = max(3L, getOption("digits") - 3L),
  ...
) {
  cat("\nMean of Complexities\n")
  cat(x$mean, "\n")
  cat("\nStandard Deviation of Complexities\n")
  cat(x$sd, "\n")
  cat("\nStandard Error of Complexities\n")
  cat(x$se)
  invisible(x)
}

#' Pander Method for hagis Summary Complexities
#'
#' Prints a \CRANpkg{hagis} complexities summary in Pandoc's markdown.
#' @param x a `complexities` object
#' @param caption caption (string) to be shown under the table
#' @param ... optional parameters passed to raw `pandoc.table` function
#' @importFrom pander pander
#' @export
#' @noRd
pander.summary.complexities <-
  function(x, caption = attr(x, "caption"), ...) {
    pander::pandoc.table(
      data.frame(Mean = x[[1L]], SD = x[[2L]], SE = x[[3L]]),
      caption = caption,
      ...
    )
  }

#' Prints hagis.complexities Object
#'
#' Custom [print()] method for `hagis.complexity` objects.
#'
#' @param x a hagis.complexities object
#' @param ... ignored
#' @export
#' @noRd
print.hagis.complexities <- function(
  x,
  digits = max(3L, getOption("digits") - 3L),
  ...
) {
  cat("\nGrouped Complexities\n")
  print(x[[1L]])
  cat("\n")
  cat("\nIndividual Complexities\n")
  print(x[[2L]])
  cat("\n")
  invisible(x)
}
